---
title: "Result reports of 'paper_template'"
author: 
  - name: ""
    affiliation: ""
affiliation:
    
  - id: ""
    institution: ""
date: "`r Sys.Date()`"
header-includes:  |
  \usepackage{placeins}
floatsintext: yes
linenumbers: no 
draft: no
mask: no
figurelist: no
tablelist: no
footnotelist: no
classoption: "doc"
output: 
  # papaja::apa6_pdf:
  #   keep_tex: true
  papaja::apa6_docx: default
always_allow_html: true
---

```{r setup, include=FALSE}
# Figure out output format
is_docx <- knitr::pandoc_to("docx") | knitr::pandoc_to("odt")
is_latex <- knitr::pandoc_to("latex")
is_html <- knitr::pandoc_to("html")

# Word-specific things
table_format <- ifelse(is_docx, "huxtable", "kableExtra")  # Huxtable tables
conditional_dpi <- ifelse(is_docx, 300, 300)  # Higher DPI
conditional_align <- ifelse(is_docx, "default", "center")  # Word doesn't support align

# Knitr options
knitr::opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE,
  # tidy.opts = list(width.cutoff = 120),  # Code width
  # fig.retina = 3, dpi = conditional_dpi,
  fig.width = 7, fig.asp = 0.618,
  # fig.align = conditional_align, out.width = "100%",
  fig.path = "figures/"
  # cache.path = "output/_cache/",
  # fig.process = function(x) {  # Remove "-1" from figure names
  #   x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  #   if (file.rename(x, x2)) x2 else x
  # },
  # options(scipen = 99999999)  # Prevent scientific notation
)

# R options
options(
  width = 90,  # Output width
  dplyr.summarise.inform = FALSE,  # Turn off dplyr's summarize() auto messages
  knitr.kable.NA = "",  # Make NAs blank in kables
  kableExtra.latex.load_packages = FALSE,  # Don't add LaTeX preamble stuff
  modelsummary_factory_default = table_format,  # Set modelsummary backend
  modelsummary_format_numeric_latex = "plain"  # Don't use siunitx
)

```

```{r libraries, include=FALSE}
library(tidyverse)
library(flextable)
library(papaja)
library(lmerTest)
library(broom)
library(broom.mixed)
```

```{r functions}
# round numbers from models
rounded_numbers <- function(x) mutate_if(x, is.numeric, round, 2)

# get model outputs ready for inline text reporting
clean_lm <- function(model_output) {
  
  result <- tidy(model_output, conf.int = TRUE) %>%
    # filter(effect == "fixed") %>% 
    # report p.value according to apa standards
    mutate(p.value = case_when(p.value < 0.001 ~ "< .001",
                               TRUE ~ paste0("= ", sprintf("%.3f", p.value))
    )
    ) %>% 
    # all other terms
    rounded_numbers() %>% 
    mutate(
      term = ifelse(term == "(Intercept)", "intercept", term),
      ci = glue::glue("[{conf.low}, {conf.high}]"), 
      # if there is an interaction (recognized by ":"), name it just interaction
      term = str_replace(term, ".*:.*", "interaction")
    ) %>% 
    select(term, estimate, std.error, ci, p.value) %>% 
    split(.$term)
  
  model_fit = glance(model_output) %>% 
    select(adj.r.squared, df.residual, df, statistic, p.value) %>% 
    rounded_numbers() %>% 
    mutate_all(~ {attributes(.) <- NULL; .})
  
  result$model_fit = model_fit
  
  return(result)
}

clean_lmer <- function(model_output) {
  
  result <- broom.mixed::tidy(model_output, conf.int = TRUE) %>%
    filter(effect == "fixed") %>% 
    # report p.value according to apa standards
    mutate(p.value = case_when(p.value < 0.001 ~ "< .001",
                               TRUE ~ paste0("= ", sprintf("%.3f", p.value))
    )
    ) %>% 
    # all other terms
    rounded_numbers() %>% 
    mutate(
      term = ifelse(term == "(Intercept)", "intercept", term),
      ci = glue::glue("[{conf.low}, {conf.high}]"), 
      # if there is an interaction (recognized by ":"), name it just interaction
      term = str_replace(term, ".*:.*", "interaction"),
      clean_term = term %>%
          str_replace_all("factor\\(.*?\\)", "") %>%
          str_replace_all("scale\\((.*?)\\)", "\\1")
      ) %>% 
    select(clean_term, term, estimate, std.error, ci, df, statistic, p.value) %>% 
    split(.$clean_term)
  
  return(result)
}

# clean data frame results for paired t-test
clean_t_test <- function(t.test) {
  
  t.test %>% 
    tidy() %>% 
    select(-c(method, alternative)) %>% 
    # report p.value according to apa standards
    mutate(p.value = case_when(p.value < 0.001 ~ "< .001",
                               TRUE ~ sprintf("p = %.3f", p.value)
    )
    ) %>% 
    # all other terms
    rounded_numbers() %>%
    mutate_all(~ {attributes(.) <- NULL; .})
  
}
```

# Study 1




